"""
split_data.py — Split train set into train/valid (80/20).

Layout expected:
    datasets/train/images/   ← all image files
    datasets/train/labels/   ← matching .txt label files

After running:
    datasets/train/{images,labels}/   ← ~80%
    datasets/valid/{images,labels}/   ← ~20%

Also rewrites config/data.yaml with the correct paths and class names.

Usage:
    python split_data.py
    python split_data.py --ratio 0.15
    python split_data.py --seed 99
"""

import argparse
import os
import random
import shutil


TRAIN_IMAGES = os.path.join("datasets", "train", "images")
TRAIN_LABELS = os.path.join("datasets", "train", "labels")
VALID_IMAGES = os.path.join("datasets", "valid", "images")
VALID_LABELS = os.path.join("datasets", "valid", "labels")
DATA_YAML    = os.path.join("config", "data.yaml")


def parse_args():
    p = argparse.ArgumentParser(description="Split dataset into train / valid")
    p.add_argument("--ratio", type=float, default=0.20)
    p.add_argument("--seed",  type=int,   default=42)
    return p.parse_args()


def collect_stems(directory):
    stems = []
    for f in os.listdir(directory):
        name, ext = os.path.splitext(f)
        if ext.lower() in (".jpg", ".jpeg", ".png"):
            stems.append((name, ext))
    stems.sort()
    return stems


def main():
    args = parse_args()
    random.seed(args.seed)

    if not os.path.isdir(TRAIN_IMAGES):
        print(f"❌  Source folder not found: {TRAIN_IMAGES}")
        return

    all_files = collect_stems(TRAIN_IMAGES)
    total = len(all_files)
    if total == 0:
        print(f"❌  No image files found in {TRAIN_IMAGES}")
        return

    print(f"📂  Found {total} images in {TRAIN_IMAGES}")

    # Shuffle & split
    random.shuffle(all_files)
    val_count = max(1, int(total * args.ratio))
    val_files = all_files[:val_count]

    print(f"✂️   Split → train: {total - val_count}  |  valid: {val_count}  ({args.ratio:.0%})")

    # Create valid directories
    os.makedirs(VALID_IMAGES, exist_ok=True)
    os.makedirs(VALID_LABELS, exist_ok=True)

    # Move validation files
    moved_img, moved_lbl, missing_lbl = 0, 0, 0
    for stem, ext in val_files:
        src_img = os.path.join(TRAIN_IMAGES, stem + ext)
        if os.path.isfile(src_img):
            shutil.move(src_img, os.path.join(VALID_IMAGES, stem + ext))
            moved_img += 1

        src_lbl = os.path.join(TRAIN_LABELS, stem + ".txt")
        if os.path.isfile(src_lbl):
            shutil.move(src_lbl, os.path.join(VALID_LABELS, stem + ".txt"))
            moved_lbl += 1
        else:
            missing_lbl += 1

    print(f"   ✅ Moved {moved_img} images, {moved_lbl} labels to valid/")
    if missing_lbl:
        print(f"   ⚠️  {missing_lbl} image(s) had no matching label file")

    remaining_train = len(os.listdir(TRAIN_IMAGES))
    remaining_valid = len(os.listdir(VALID_IMAGES))
    print(f"\n   📊 Final counts:")
    print(f"      train/images: {remaining_train}")
    print(f"      valid/images: {remaining_valid}")

    # Rewrite data.yaml
    yaml_content = """\
# ============================================================
# YOLOv8 Dataset Configuration  (auto-generated by split_data.py)
# ============================================================

path: ../datasets
train: train/images
val: valid/images

nc: 2
names:
  0: Damaged
  1: package
"""
    os.makedirs(os.path.dirname(DATA_YAML), exist_ok=True)
    with open(DATA_YAML, "w", encoding="utf-8") as f:
        f.write(yaml_content)

    print(f"\n📝  Updated {DATA_YAML}")
    print("✅  Done!\n")


if __name__ == "__main__":
    main()
